(define-mail-abbrev "achla marathe" "achla@lanl.gov")
(define-mail-abbrev "brian bush" "bwb@lanl.gov")
(define-mail-abbrev "chris barrett" "barrett@lanl.gov")
(define-mail-abbrev "clay booker" "cxb@lanl.gov")      
(define-mail-abbrev "deborah kubicek" "kubicek@lanl.gov")
(define-mail-abbrev "dick beckman" "rjb@lanl.gov")
(define-mail-abbrev "douglas roberts" "dzzr@lanl.gov")
(define-mail-abbrev "episims code team" "eubank@lanl.gov,sxs@lanl.gov,karla@lanl.gov,dzzr@lanl.gov")
(define-mail-abbrev "gopalan" "agopalan@nmsu.edu")      
(define-mail-abbrev "goran konjevod" "goran@lanl.gov")
(define-mail-abbrev "graham mark" "gam@lanl.gov")
(define-mail-abbrev "henning s. mortveit" "henning@lanl.gov")
(define-mail-abbrev "james p. smith" "jpsmith@lanl.gov")
(define-mail-abbrev "jane riese" "jriese@lanl.gov")
(define-mail-abbrev "jeanne m. hurford" "jmh@lanl.gov")
(define-mail-abbrev "jeff steinman" "steinman@ca.metsci.com")
(define-mail-abbrev "joe holland" "holland@snark.lanl.gov")      
(define-mail-abbrev "joe pfeiffer" "pfeiffer@cs.nmsu.edu")
(define-mail-abbrev "judith cohn" "jcohn@lanl.gov")
(define-mail-abbrev "karla atkins" "karla@lanl.gov")
(define-mail-abbrev "kathryn berkbigler" "kpb@c3serve.c3.lanl.gov")
(define-mail-abbrev "kriste henson" "kriste@lanl.gov")
(define-mail-abbrev "kristi brislawn" "kdb@lanl.gov")
(define-mail-abbrev "lukas kroc" "kroc@lanl.gov")
(define-mail-abbrev "madhav marathe" "marathe@lanl.gov")
(define-mail-abbrev "marilyn yeamans" "yeamans@lanl.gov")
(define-mail-abbrev "melissa a. haway" "haway@lanl.gov")
(define-mail-abbrev "michael kolakowski school" "mkolakow@hotmail.com")
(define-mail-abbrev "mike koscielniak" "mkosciel@pagan.agps.lanl.gov")
(define-mail-abbrev "paula stretz" "stretz@lanl.gov")
(define-mail-abbrev "phil romero" "prr@mozart.tsasa.lanl.gov")
(define-mail-abbrev "randy Michelsen" "rem@lanl.gov")      
(define-mail-abbrev "rob-la" "rob@lanl.gov")      
(define-mail-abbrev "ron pistone" "pistone@lanl.gov")
(define-mail-abbrev "russell mcfadden" "mcfadden@lanl.gov")
(define-mail-abbrev "sandra hull" "shull@lanl.gov")
(define-mail-abbrev "scott yoder" "yoder@zianet.com")
(define-mail-abbrev "sean blanchard" "seanb@lanl.gov")
(define-mail-abbrev "sid sydoriak" "sxs@lanl.gov")
(define-mail-abbrev "stephan eidenbenz" "eidenben@lanl.gov")
(define-mail-abbrev "stephen eubank" "eubank@lanl.gov")
(define-mail-abbrev "steve mortenson" "stevem@sgt-york.lanl.gov")      
(define-mail-abbrev "steven fernandez" "sjf@lanl.gov")
(define-mail-abbrev "sue mniszewski" "smm@lanl.gov")
(define-mail-abbrev "tim cleland" "cleland@lanl.gov")
(define-mail-abbrev "transims sowftware" "transims-sw@lanl.gov")
(define-mail-abbrev "wendy lanl" "wcb@lanl.gov")      
(define-mail-abbrev "wendy pager" "1044734.page@lanl.gov")
(define-mail-abbrev "sibylle zust" "zust@lanl.gov")
(define-mail-abbrev "uis software" "uis-software@lanl.gov")
(define-mail-abbrev "Michael Kolakowski" "kolako@lanl.gov")
(define-mail-abbrev "dave tallman" "ctallman@lanl.gov")
(define-mail-abbrev "Randy Bosetti" "bosetti@lanl.gov")
(define-mail-abbrev "Doug Anson" "anson@lanl.gov")
(define-mail-abbrev "ccs5-help" "ccs5-help@lanl.gov")
(define-mail-abbrev "uis-software" "uis-software@lanl.gov")
(define-mail-abbrev "Kimberly Gonzales" "kgonz@lanl.gov")
(define-mail-abbrev "*Correspondence" "*Correspondence*")
(define-mail-abbrev "ADC" "Unclassified, ADC reviewed by:")
(define-mail-abbrev "dusa" "DUSA: LASCI-OS, LASCI-CS")
